import asyncHandler from "../middleware/asyncHandler.js";
import Order from "../models/order.js";
import {
    getInvoiceByOrderId,
    getInvoiceById,
    regenerateInvoicePdf,
    resendInvoiceEmail,
} from "../services/invoiceService.js";

/**
 * @desc   Get invoice metadata by order ID
 * @route  GET /api/invoices/order/:orderId
 * @access Private (owner or admin)
 */
export const getInvoiceByOrder = asyncHandler(async (req, res) => {
    const { orderId } = req.params;

    // Validate order exists and ownership
    const order = await Order.findById(orderId);

    if (!order) {
        return res.status(404).json({
            success: false,
            message: "Order not found.",
        });
    }

    // Security: Only owner or admin
    if (
        order.user.toString() !== req.user._id.toString() &&
        req.user.role !== "admin"
    ) {
        return res.status(403).json({
            success: false,
            message: "Access denied.",
        });
    }

    const invoice = await getInvoiceByOrderId(orderId);

    if (!invoice) {
        return res.status(404).json({
            success: false,
            message: "Invoice not found for this order.",
        });
    }

    console.log(
        `[INVOICE] 📋 Invoice metadata retrieved: ${invoice.invoiceNumber} by user ${req.user._id}`
    );

    res.status(200).json({
        success: true,
        invoice,
    });
});

/**
 * @desc   Download invoice PDF by order ID
 * @route  GET /api/invoices/download/:orderId
 * @access Private (owner or admin)
 */
export const downloadInvoicePdf = asyncHandler(async (req, res) => {
    const { orderId } = req.params;

    // Validate order exists and ownership
    const order = await Order.findById(orderId);

    if (!order) {
        return res.status(404).json({
            success: false,
            message: "Order not found.",
        });
    }

    // Security: Only owner or admin
    if (
        order.user.toString() !== req.user._id.toString() &&
        req.user.role !== "admin"
    ) {
        console.warn(
            `[INVOICE] 🚫 Unauthorized download attempt by user ${req.user._id} for order ${orderId}`
        );

        return res.status(403).json({
            success: false,
            message: "Access denied.",
        });
    }

    const invoice = await getInvoiceByOrderId(orderId);

    if (!invoice) {
        return res.status(404).json({
            success: false,
            message: "Invoice not found for this order.",
        });
    }

    if (!invoice.pdfUrl) {
        return res.status(404).json({
            success: false,
            message: "Invoice PDF not available. Please try again later.",
        });
    }

    // Update status to Downloaded
    if (invoice.status !== "Downloaded") {
        invoice.status = "Downloaded";
        await invoice.save();
    }

    console.log(
        `[INVOICE] ⬇️  Invoice downloaded: ${invoice.invoiceNumber} by user ${req.user._id}`
    );

    // Redirect to Cloudinary PDF URL for download
    res.redirect(invoice.pdfUrl);
});

/**
 * @desc   Resend order confirmation email (admin)
 * @route  POST /api/invoices/:invoiceId/resend-email
 * @access Private/Admin
 */
export const resendEmail = asyncHandler(async (req, res) => {
    const { invoiceId } = req.params;

    await resendInvoiceEmail(invoiceId);

    console.log(
        `[INVOICE] 📧 Email resend triggered by admin ${req.user._id} for invoice ${invoiceId}`
    );

    res.status(200).json({
        success: true,
        message: "Confirmation email resent successfully.",
    });
});

/**
 * @desc   Regenerate invoice PDF (admin)
 * @route  POST /api/invoices/:invoiceId/regenerate-pdf
 * @access Private/Admin
 */
export const regeneratePdf = asyncHandler(async (req, res) => {
    const { invoiceId } = req.params;

    const invoice = await regenerateInvoicePdf(invoiceId);

    console.log(
        `[INVOICE] 🔄 PDF regenerated by admin ${req.user._id} for invoice ${invoiceId}`
    );

    res.status(200).json({
        success: true,
        message: "Invoice PDF regenerated successfully.",
        invoice,
    });
});
